config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  mount Crono::Web, at: '/crono'
  resources :realms
  root to: 'realms#index'
end

app/models/auction_item.rb
class AuctionItem < ActiveRecord::Base
  validates :character_id, :realm_id, :bid, :buyout, :quantity, :time_left,
            :item_id, :auc, presence: true
  belongs_to :character
  belongs_to :item
  belongs_to :realm

  scope :active, -> { where(time_left: %w(VERY_LONG LONG MEDIUM SHORT)) }
  scope :inactive, -> { where(time_left: 'NONE') }
end

app/models/auction_worker.rb
class AuctionWorker
  include Sidekiq::Worker
  def perform(realm_id)
    realm = Realm.find(realm_id)
    realm.download_json
  end
end

app/models/character.rb
class Character < ActiveRecord::Base
  has_many :auction_items, dependent: :destroy

  validates :name, presence: true
  validates :realm_id, presence: true
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :auction_items

  validates :wow_id, presence: true, uniqueness: true

  def self.get_and_save(item_id)
    item = Item.find_or_initialize_by(wow_id: item_id)

    remote_item = Wowrb.item(item_id)

    item.name = remote_item['name']
    item.save

    item
  end
end

app/models/realm.rb
class Realm < ActiveRecord::Base
  has_many :characters, dependent: :destroy
  has_many :auction_items, dependent: :destroy
  validates :name, presence: true

  def refresh_data
    AuctionWorker.perform_async(id)
  end

  def download_json
    auction_info = get_auction_url

    if last_modified != auction_info[:last_modified].to_s
      update(last_modified: auction_info[:last_modified].to_s)

      response = HTTParty.get(auction_info[:url])
      open("public/temp/#{name}.json", 'wb') do |file|
        file.write(response.body)
      end

      parse_json
    end
  end

  def parse_json
    file = File.read("public/temp/#{name}.json")
    hash = JSON.parse(file)
    auc_ids = hash['auctions'].map { |a| a['auc'] }

    AuctionItem.active.each do |item|
      unless auc_ids.include?(item.auc)
        item.update(time_left: 'NONE')
      end
    end

    hash['auctions'].each do |lot|
      owner = Character.find_or_initialize_by(
        name: lot['owner'], realm_id: id
      )
      owner.goods += 1
      owner.save!

      item = Item.get_and_save(lot['item'])

      AuctionItemWorker.perform_async(lot, item.id, owner.id, id)
    end
  end

  private

  def get_auction_url
    response = Wowrb.auction_url(name)
    {
      url: response['files'].first['url'],
      last_modified: response['files'].first['lastModified']
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/realms_controller.rb
class RealmsController < ApplicationController
  before_action :set_realm, only: [:show, :edit, :update, :destroy]

  def index
    @realms = Realm.includes(:characters)
                   .includes(:auction_items)
                   .order(name: :asc)
    @items_count = Item.count
    @characters_count = Character.count
    @auction_items_count = AuctionItem.count
  end

  def show
    # @top_sellers = @realm.characters
    #                      .joins(:auction_items)
    #                      .group("characters.id")
    #                      .order("count(characters.id) DESC")
    #                      .first(10)

    @top_sellers = @realm.characters.order(goods: :desc).first(10)
  end

  def new
    @realm = Realm.new
  end

  def edit
  end

  def create
    @realm = Realm.new(realm_params)

    if @realm.save
      redirect_to @realm, notice: 'Realm was successfully created.'
    else
      render :new
    end
  end

  def update
    if @realm.update(realm_params)
      redirect_to @realm, notice: 'Realm was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @realm.destroy
    redirect_to realms_url, notice: 'Realm was successfully destroyed.'
  end

  private
    def set_realm
      @realm = Realm.find(params[:id])
    end

    def realm_params
      params.require(:realm).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def to_gold(amount)
    amount = amount.to_i
    gold = amount / 10000
    remainder = amount % 10000
    silver = remainder / 100
    copper = remainder % 100

    "#{gold}g #{silver}s #{copper}c"
  end
end

app/helpers/realms_helper.rb
module RealmsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trump</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class='container'>

<%= render 'shared/navbar' %>
<%= yield %>

<script type='text/javascript' src='//wow.zamimg.com/widgets/power.js'></script><script>var wowhead_tooltips = { 'colorlinks': true, 'iconizelinks': true, 'renamelinks': true }</script>
</body>
</html>

app/views/realms/_form.html.slim
= simple_form_for(@realm) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit

app/views/realms/edit.html.slim
h1 Editing realm

== render 'form'

= link_to 'Show', @realm
'|
= link_to 'Back', realms_path

app/views/realms/index.html.slim
h1 Listing realms

h3 = "#{@items_count} items total"
h3 = "#{@auction_items_count} auction items total"
h3 = "#{@characters_count} characters total"

table.table.table-bordered
  thead
    tr
      th
      th
      th Auction Items Total
      th Characters total
      th Last updated

  tbody
    - @realms.each do |realm|
      tr
        td = link_to realm.name, realm
        td = link_to 'Edit', edit_realm_path(realm)
        td = realm.auction_items.size
        td = realm.characters.size
        td = "#{time_ago_in_words(realm.updated_at)} ago"

app/views/realms/new.html.slim
h1 New realm

== render 'form'

= link_to 'Back', realms_path

app/views/realms/show.html.slim
h2 = "Name: #{@realm.name}"

h3 Top sellers

- @top_sellers.each do |character|
  li = "#{character.name } (#{character.goods})"

table.table.table-bordered.bg-info
  tr
    th Предмет
    th Персонаж
    th Ставка
    th Выкуп
    th Оставшееся время
  - @realm.auction_items.last(5).each do |item|
    tr
      td
        => link_to "#{item.item.name}", '#', rel: "item=#{item.item.wow_id} domain=ru"
        = "(#{item.quantity})"
      td = item.character.name
      td = to_gold(item.bid)
      td = to_gold(item.buyout)
      td = item.time_left

= link_to 'Edit', edit_realm_path(@realm)

app/views/shared/_navbar.slim
nav.navbar.navbar-default role="navigation"
  .container-fluid
    .navbar-header
      button.navbar-toggle data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Trump', root_path, class: 'navbar-brand'
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav
        li.active
          a href="#"  Link
        li
          a href="#"  Link
        li.dropdown
          a.dropdown-toggle data-toggle="dropdown" href="#"
            | Dropdown
            span.caret
          ul.dropdown-menu role="menu"
            li
              a href="#"  Action
            li
              a href="#"  Another action
            li
              a href="#"  Something else here
            li.divider
            li
              a href="#"  Separated link
            li.divider
            li
              a href="#"  One more separated link
      form.navbar-form.navbar-left role="search"
        .form-group
          input.form-control placeholder="Search" type="text"
        button.btn.btn-default type="submit"  Submit
      ul.nav.navbar-nav.navbar-right
        li
          a href="#"  Link
        li.dropdown
          a.dropdown-toggle data-toggle="dropdown" href="#"
            | Dropdown
            span.caret
          ul.dropdown-menu role="menu"
            li
              a href="#"  Action
            li
              a href="#"  Another action
            li
              a href="#"  Something else here
            li.divider
            li
              a href="#"  Separated link